export const usersData = [
  {
    id: 1,
    name: "John Doe",
    age: 28,
    email: "john@example.com",
    phoneNumber: "123-456-7890",
    address: "123 Main St, Cityville",
    jobTitle: "Software Engineer",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 34,
    email: "jane@example.com",
    phoneNumber: "987-654-3210",
    address: "456 Oak St, Townsville",
    jobTitle: "Project Manager",
  },
  {
    id: 3,
    name: "Michael Johnson",
    age: 21,
    email: "michael@example.com",
    phoneNumber: "555-123-4567",
    address: "789 Pine St, Villageville",
    jobTitle: "Intern",
  },
  {
    id: 4,
    name: "Emily Davis",
    age: 40,
    email: "emily@example.com",
    phoneNumber: "321-654-9870",
    address: "321 Maple St, Hamletville",
    jobTitle: "CTO",
  },
  {
    id: 5,
    name: "Daniel Wilson",
    age: 23,
    email: "daniel@example.com",
    phoneNumber: "654-321-0987",
    address: "567 Elm St, Metropolis",
    jobTitle: "Marketing Specialist",
  },
  {
    id: 6,
    name: "Sarah Brown",
    age: 31,
    email: "sarah@example.com",
    phoneNumber: "111-222-3333",
    address: "135 Cedar St, Boroughville",
    jobTitle: "UI/UX Designer",
  },
  {
    id: 7,
    name: "David White",
    age: 29,
    email: "david@example.com",
    phoneNumber: "444-555-6666",
    address: "246 Birch St, Hamletville",
    jobTitle: "DevOps Engineer",
  },
  {
    id: 8,
    name: "Jessica Green",
    age: 25,
    email: "jessica@example.com",
    phoneNumber: "777-888-9999",
    address: "987 Spruce St, Megacity",
    jobTitle: "Product Designer",
  },
];
